import { useState } from "react";
import Head from "next/head";
import CssBaseline from "@mui/material/CssBaseline";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import SubjectForm from "../components/SubjectForm";
import Summary from "../components/Summary";

export default function Home() {
  const [formOpen, setFormOpen] = useState(false);
  const [data, setData] = useState([]);
  const [target, setTarget] = useState(405);

  const handleFormSubmit = (values) => {
    setData([...data, values]);
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />

      <main>
        <Typography variant="h1">Izračun satnice</Typography>

        {data.length > 0 && <Summary data={data} target={target} />}

        <Button variant="contained" onClick={() => setFormOpen(true)}>
          Dodaj predmet
        </Button>
        <SubjectForm
          open={formOpen}
          onClose={() => setFormOpen(false)}
          onSubmit={handleFormSubmit}
        />
      </main>
    </Container>
  );
}
